Выполнено первое д/з.
danilasimanok/ComputerDataProcessingAlgorithms-2- pull request #1
Opened 2020-04-09 18:20 UTC by danilasimanok

2020-04-10 12:08 UTC, yurii-litvinov requested changes
По существу всё правильно, но местами проблемы с оформлением кода. Пусть все, кроме Фибоначчи будут зачтены, а Фибонччи надо будет поправить

2020-04-10 12:08 UTC, yurii-litvinov commented on .travis.yml
> +    - sudo apt-get install nuget
Мне кажется, на travis nuget предустановлен

2020-04-10 12:08 UTC, yurii-litvinov commented on .travis.yml
> +    - dotnet test hw1/tasks/tasks.sln
И dotnet test должен вызвать dotnet build по идее

2020-04-10 12:08 UTC, yurii-litvinov commented on hw1/tasks/Required/Library.fs
> +    let fib n =
Это плохое имя для функции. Возникает вопрос "fib что?". Fiber, Fibonacci, Fibromyalgia?

2020-04-10 12:08 UTC, yurii-litvinov commented on hw1/tasks/Required/Library.fs
> +            else Some(inner 0 1 1 n)
Красивее было бы match-ем

2020-04-10 12:08 UTC, yurii-litvinov commented on hw1/tasks/Required/Library.fs
> +    let powers_of_2 n m =
В F# уже давно не используется snake_case, начиная с версии 3 где-то. Надо в camelCase, `powersOf2`

2020-04-10 12:08 UTC, yurii-litvinov commented on hw1/tasks/Required/Library.fs
> +            else inner n sum (if i >=n then (current :: acc) else acc) (i + 1) (2 * current)
`>=n` --- пробела не хватает

2020-04-10 12:08 UTC, yurii-litvinov commented on hw1/tasks/Tests/LibraryTests.fs
> +        match fib n, fib (n-1), fib (n-2) with
Тут уж совсем не хватает пробелов. Бинарные операции всегда выделяются пробелами

2020-04-10 18:39 UTC, danilasimanok commented on .travis.yml
> +    - sudo apt-get install nuget
К сожалению, нет.

2020-04-12 19:25 UTC, yurii-litvinov commented on .travis.yml
> +    - sudo apt-get install nuget
И правда, нету

2020-04-12 19:26 UTC, yurii-litvinov approved these changes
Ага, всё ок, зачтена. Единственное что когда отправляете исправление, имеет смысл прикладывать всё равно ссылку на пуллреквест, а не на конкретный коммит, потому что в исправлении вряд ли всего один коммит будет

2020-04-17 14:10 UTC, merged